# Question
Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log('Inside the loop', i);
  }
  console.log('Outside the loop');
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer
No, the `console.log('Outside the loop');` will never run. The for loop iterates from i = 0 to i = 4. However, inside the for loop, there is a condition of if (i > 3) then return;. When i is greater than 3, the function will exit and no code within the loop or after will be executed. If i becomes greater than 3, the `console.log('Outside the loop');` statement will never be reached. 

# Teacher Feedback
